
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abbu123
      MYSQL_DATABASE: projectsumath
      MYSQL_USER: abbu
      MYSQL_PASSWORD: abbu123
    ports:
      - "3307:3306"   # host:container (use 3307 on your PC)
    networks:
      - s-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./projectsumath.sql:/docker-entrypoint-initdb.d/projectsumath.sql

  app:
    build: .
    container_name: spring-app-contact
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/projectsumath
      SPRING_DATASOURCE_USERNAME: abbu
      SPRING_DATASOURCE_PASSWORD: abbu123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "3333:3333"
    networks:
      - s-network
    depends_on:
      - mysql-db

volumes:
  mysql_data:
networks:
  s-network:
    driver: bridge



















#version: "3.7"
#
#services:
#  app:
#    build:
#      ports:
#        - 3333:3333
#      networks:
#        s-network
#  mysql-db:
#    image: mysql:latest
#    environment:
#      MYSQL_DATABASE: projectsumath
#      MYSQL_USER: abdul
#      MYSQL_PASSWORD: abbu123
#    ports:
#      - 3306:3306
#    networks:
#      s-network

#networks:
#  s-network:
#    driver: bridge

