server:
  port: 8181
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: abbu123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true	