server:
  port: 8081
spring:
  application:
    name: user-service
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111/

  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/fitness-user-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

        