#server:
#  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: activity-service
#              uri: lb://ACTIVITY-SERVICE
#              predicates:
#                - Path=/activities/api/**
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/users/api/**
#            - id: ai-service
#              uri: lb://AI-SERVICE
#              predicates:
#                - Path=/recommendations/api/**
