#server:
#  port: 8081
spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111/
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: abbu123
#    url: jdbc:mysql://localhost:3306/orders_db
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#