server:
  port: 8082
spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fitness_activity_db
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    name: activity-events





#  datasource:
#    username: root
#    password: abbu123
#    url: jdbc:mysql://localhost:3306/fitness_activity_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


