server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: abbu123
    url: jdbc:postgresql://localhost:5432/fitness-user-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



